colorscheme Tomorrow-Night

if has('gui_running')
  set guifont=Source\ Code\ Pro:h13
endif

:set tabstop=2
:set shiftwidth=2
:set expandtab
:set ruler
:set number

if has("gui_running")
  au BufRead * let &numberwidth = float2nr(log10(line("$"))) + 2
          \| let &columns = &numberwidth + 120
  set lines=80
endif
