# Path to your oh-my-zsh configuration.
ZSH=$HOME/src/config/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME=""
ZSH_2000_DISABLE_RVM='true'

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

PATH="$HOME/src/config/bin:$PATH"

source $ZSH/oh-my-zsh.sh

fpath+=$HOME/src/config/pure
autoload -U promptinit; promptinit
prompt pure

RC_FILES_PATH=$HOME/.rc
if [ -d $RC_FILES_PATH ]
then
  for c in `ls $RC_FILES_PATH`; do
    source $RC_FILES_PATH/$c
  done
fi
